version: 0.2

phases:
  pre_build:
  commands:
  - echo Logging in to Amazon ECR...
  - aws --version
  - $(aws ecr get-login --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin (ecr repository link (URI))
  - REPOSITORY_URI=YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/YOUR_REPO
  - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  - IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definition file 
    - printf '[{"name":"flask-container" ${Name of the container},"imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > taskdef.json
    - sed -i -e "s|<REPOSITORY_URI_PLACEHOLDER>|${$REPOSITORY_URI}:${IMAGE_TAG}|g" taskdef.json
    - aws ecs register-task-definition --cli-input-json file://taskdef.json --region us-west-2

